name: Local
values:
  - key: BASE_URL
    value: 'http://localhost:3000'
  - key: PHP_URL
    value: 'http://localhost:8080'
  - key: TOKEN_ADMIN
    value: ''
  - key: TOKEN_USER
    value: ''
  - key: TOKEN_COMPANY
    value: ''
  - key: TOKEN_STUDENT
    value: ''
  - key: COURSE_ID
    value: ''
  - key: JOB_ID
    value: ''
  - key: MEMBER_ID
    value: ''
  - key: APPLICATION_ID
    value: ''
color: 120
